name: 'Drift Detection'

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Drift Detection'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        role-session-name: MySessionName

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terrafor and outputs an exit code 
    - name: Terraform Plan
      run: |
        terraform plan -detailed-exitcode
        EXITCODE=$?
        if [ $EXITCODE -eq 2 ]; then
          echo "Changes detected in the plan"
          exit 1
        elif [ $EXITCODE -eq 0 ]; then
          echo "No changes detected"
          exit 0
        else
          echo "Error running plan"
          exit 1
        fi